"""Domain models – re-exported from sub-modules for backward compatibility."""

from novel_writer.domain.approval import (
    Approval,
    ApprovalDecision,
    ApprovalTarget,
    BriefOption,
    BriefScenePlan,
    ChapterBrief,
)
from novel_writer.domain.base import FrozenModel, Identified
from novel_writer.domain.character import (
    Character,
    CharacterBelief,
    CharacterMindState,
    CharacterPortrayalProfile,
    CharacterRelationship,
    CharacterVoiceExample,
    InternalConflict,
    MindBelief,
    MindDrive,
    MindEmotion,
)
from novel_writer.domain.plot import (
    EvidenceSpan,
    Foreshadowing,
    ForeshadowingLifecycleEvent,
    FormalBodyEvidence,
    OpenQuestion,
    PlotThread,
    ReaderDisclosure,
    ReaderPromise,
    ReaderPromiseEvidence,
    ReaderPromiseUpdate,
)
from novel_writer.domain.state import StateDelta, StateVersion, StoryState
from novel_writer.domain.story import (
    Chapter,
    NarrativePhase,
    NarrativePosition,
    PlotHistoryDecision,
    ScheduledDevelopment,
    StoryForce,
    StoryFoundation,
    StoryProject,
)
from novel_writer.domain.world import (
    Place,
    Scene,
    StoryEvent,
    TimelineConstraint,
    WorldLoreEntry,
    WorldRule,
)

__all__ = [
    "Approval",
    "ApprovalDecision",
    "ApprovalTarget",
    "BriefOption",
    "BriefScenePlan",
    "Chapter",
    "ChapterBrief",
    "Character",
    "CharacterBelief",
    "CharacterMindState",
    "CharacterPortrayalProfile",
    "CharacterRelationship",
    "CharacterVoiceExample",
    "EvidenceSpan",
    "FormalBodyEvidence",
    "Foreshadowing",
    "ForeshadowingLifecycleEvent",
    "FrozenModel",
    "Identified",
    "InternalConflict",
    "MindBelief",
    "MindDrive",
    "MindEmotion",
    "NarrativePhase",
    "NarrativePosition",
    "OpenQuestion",
    "Place",
    "PlotHistoryDecision",
    "PlotThread",
    "ReaderDisclosure",
    "ReaderPromise",
    "ReaderPromiseEvidence",
    "ReaderPromiseUpdate",
    "Scene",
    "ScheduledDevelopment",
    "StateDelta",
    "StateVersion",
    "StoryEvent",
    "StoryForce",
    "StoryFoundation",
    "StoryProject",
    "StoryState",
    "TimelineConstraint",
    "WorldLoreEntry",
    "WorldRule",
]
